on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 * * * *' # Every hour
  push:
    tags:
    - '*'
  pull_request:
    types: [opened, edited]
name: Package manager test
jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/install-test.sh
          sparse-checkout-cone-mode: false
      - run: bash scripts/install-test.sh homebrew
  apt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/install-test.sh
          sparse-checkout-cone-mode: false
      - run: bash scripts/install-test.sh apt
  yum:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - run: |
          if [ ! -d "/etc/yum.repos.d" ]; then
              sudo mkdir /etc/yum.repos.d
          fi
              echo "[Stripe]
          name=stripe
          baseurl=https://packages.stripe.dev/stripe-cli-rpm-local/
          enabled=1
          gpgcheck=0" | sudo tee /etc/yum.repos.d/stripe.repo

      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/install-test.sh
          sparse-checkout-cone-mode: false
      - run: bash scripts/install-test.sh yum
  scoop:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          scripts/install-test.sh
        sparse-checkout-cone-mode: false
    - uses: MinoruSekine/setup-scoop@v4
    - shell: powershell
      run: bash scripts/install-test.sh scoop
  docker:
    runs-on: ubuntu-latest
    container: stripe/stripe-cli:latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            scripts/install-test.sh
          sparse-checkout-cone-mode: false
      - run: sh scripts/install-test.sh docker
  pagerduty:
    needs: [docker, scoop, yum, apt, homebrew]
    runs-on: ubuntu-latest
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Send PagerDuty alert on failure
        uses: Entle/action-pagerduty-alert@0.2.0
        with:
          pagerduty-integration-key: '${{ secrets.PAGERDUTY_INTEGRATION_KEY }}'
          pagerduty-dedup-key: package_manager_install_workflow_failed
